### ISSUE TITLE
AJS37 Input

### ISSUE THREAD

**Issue by TheBigDustin** [silentwarrior/sw_dcsw_custom_binds#1]
Eagle Dynamics\DCS World\Mods\aircraft\AJS37\Input\Joystick

default.lua

https://pastebin.com/2YAsbeVR

**Comment by joaomcarlos** [comment]
Thank you :)

**Comment by joaomcarlos** [comment]
Hi.
I am back from my business trip.

Added to the repo!
I added it as "SilentWarriorSwitches" section to keep it consistent with the other ones, is that ok?
I can rename them if you want, after all you deserve the credit!

If you have switches for other aircraft please let me know and i will add them

Thanks again for the help :)

**Comment by TheBigDustin** [comment]
to be fair, i didnt create this .lua file. you can name it whatever you
wish :)
